ReaTeam/Extensions

API/brumbear_ReaKontrol.ext

- Improved keyboard detection and connection mechanism
- Diagnostic messages to user about connection state
- Allow hot plugging of keyboard after launch of Reaper

Release ReaKontrol v0.95

---

API/brumbear_ReaKontrol.ext

- Code Optimization (reduced CPU load)
- COUNT IN behavior optimized (see Reaper forum for details)
- MIDI protocol pinned to NIHIA version 2

Release ReaKontrol v0.96

---

API/brumbear_ReaKontrol.ext

- added CUSTOM ACTIONS functionality
- user editable configuration file

Release ReaKontrol v1.00

---

API/brumbear_ReaKontrol.ext
Control Surfaces/brumbear_ReaKontrol.ext

- added CUSTOM ACTIONS functionality
- user editable configuration file
- v1.00a: fixed URL link to reakontrol.ini

Release ReaKontrol v1.00a

---

API/reaper_imgui.ext

• Add a HTML documentation page (accessible from the demo: Tools->Documentation)
• Cleanup documentation of many functions (proofread, add hyperlinks...)
• Demo: fix even/odd detection in Tabs->Advanced & Close Button
API changes:
• Add PointConvertNative [p=2456542]
• Remove redundant return values in the Python binding
• Rename wrongly named function PathFillConvex to DrawList_PathFillConvex

Release ReaImGui: ReaScript binding for Dear ImGui v0.5.1

---

API/reaper_imgui.ext

• Documentation: group all functions and constants by category
• Documentation: hide write-only arguments from the Lua and Python signatures
• Documentation: omit printing "double" type for arguments in EEL signatures
• macOS: fix REAPER's defer timer stopping on Big Sur [p=2458897]

Release ReaImGui: ReaScript binding for Dear ImGui v0.5.2

---

API/reaper_imgui.ext

• Demo: fix crash in the Querying Status section [p=2480715]
• Fix visibility of popups and menus opened directly over REAPER's main window
• Support WindowFlags_TopMost in BeginPopup and BeginPopupModal

Release ReaImGui: ReaScript binding for Dear ImGui v0.5.7

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

Fixed 'ReaLlm: REAPER Low latency monitoring' actions list toggle

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.3.1

---

Control Surfaces/brumbear_ReaKontrol.ext

- Support both VST2 and VST3
- Configuration file reakontrol.ini is auto generated on first startup

Release ReaKontrol v1.10

---

FX/ak5k_ReaFab Fabulous REAPER plug-in controller extension.ext

Updated some outdated parameter mappings.

Release ReaFab: Fabulous REAPER plug-in controller extension v0.3.11

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

Fixed possible crash when deleting monitored tracks while ReaLlm is enabled.
Minor API changes, see ReaScript API documentation.
Option to include Monitoring FX via API.
Option to set parameter change (instead of FX enable/disable) via API.

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.4.1

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

Fixed latency calculation for split routes
New options for Llm_Set
Reverted PARAMCHANGE delimiter back to ;

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.4.3

---

API/reaper_imgui.ext

• Fix imgui.lua always applying all available shims

Release ReaImGui: ReaScript binding for Dear ImGui v0.8.7.1

---

FX/frabert_ogler.ext

Release Ogler v0.10.0

---

Control Surfaces/ak5k_ReaSolotus REAPER Solo bus extension.ext

Release ReaSolotus: REAPER Solo bus extension v0.1.8

---

API/ak5k_ReaMCULive Programmable ReaScript API control surface extension.ext

Release ReaMCULive: Programmable ReaScript API control surface extension v0.1.7

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

Requires REAPER 7
new API
lots of code refactoring
fix the flickering bug
fix memory leak (0.6.0 regression)

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.6.1

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

improved compatibility with older REAPER version 
improved pdc calculation with different chain pdc modes

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.6.2

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

Llm_SetSafed() now matches original FX name in addition to renamed_name

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.6.3

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.6.4

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.6.5

---

API/ak5k_ReaBlink.ext

Release ReaBlink: Ableton Link REAPER plug-in extension v0.5.6

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.6.6

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.6.7

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

improved handling of loading and storing state between sessions per project
improved bug fix on FX getting 'safed' without user interaction

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.6.8

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

fix false FX chain pdc mode detection in REAPER versions 6.72 - 7.05

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.6.9

---

FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext

fix checking if send to parent folder is not active

Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.6.10

---

API/reaper_imgui.ext

• Fix a potential crash when removing textures
• Windows: repair drag-docking functionality [#23]

Release ReaImGui: ReaScript binding for Dear ImGui v0.9.3.1

---

Control Surfaces/ak5k_ReaSolotus REAPER Solo bus extension.ext

Add multi-channel support (by kronihias)

Release ReaSolotus: REAPER Solo bus extension v0.2.1

---

Control Surfaces/navelpluisje_ReaSonus Native.ext

Release ReaSonus Native v0.1.1
