- API/reaper_imgui.ext
- API/reaper_imgui/ReaImGui_Demo.lua
- API/reaper_imgui/ReaImGui_Hello World (legacy syntax).eel
- API/reaper_imgui/ReaImGui_Hello World.eel
• Add EEL2 example using the legacy < 5.24 syntax [#1]
• Fix first frame having twice the contents in the example scripts
• macOS: process the first click over an unfocused window
• Remove focus from ImGui input controls when the context window itself loses focus
Docking bugfixes:
• Fix keyboard input going to REAPER when docked
• Skip rendering when docked and another docker tab is active
• Linux & Windows: fix mousewheel events leaking to REAPER
• Linux: fix crashes, flickering and incomplete rendering
• macOS: update viewport size if it changed while another docker tab was active
• Windows: don't lose focus when Tab is pressed
> Release ReaImGui: ReaScript binding for Dear ImGui v0.1.1

- API/reaper_imgui.ext
• Add binding for Python ReaScripts (imgui_python.py)
• Correct initial context position if offscreen
• Demo: port most of the apps in the Examples menu from C++ to Lua
• Don't immediately destroy contexts created within a defer callback [p=2435994]
• Fix contexts potentially using the wrong font texture
• Fix crashes when passing nil to AcceptDragDropPayloadRGB/RGBA, Color{Edit,Picker}{3,4} and SliderAngle
• Fix invalid DrawList and Viewport pointers from EEL in 64-bit builds
• Fix using GetConfigFlags and SetConfigFlags across different contexts
• Improve clamping of default position to screen boundary
• Linux: fix initial window position on GNOME [p=2431010]
• Linux: implement HiDPI scaling
• macOS: emit key press/release events for modifier keys
• macOS: match Windows virtual key …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.3

- API/reaper_imgui.ext
• Don't run during project load or while the ReaScript defer loop is blocked
• Linux: fix Gdk-CRITICAL warning when creating an undocked context with stored docker ID
API changes:
• Remove the Freeze function that was added in v0.3
> Release ReaImGui: ReaScript binding for Dear ImGui v0.3.1

- API/reaper_imgui.ext
• Fix incorrect vertical position in some versions of macOS [p=2443450]
• Only pause during project load in REAPER 6.11 and newer
> Release ReaImGui: ReaScript binding for Dear ImGui v0.3.2

- API/reaper_imgui.ext
• Add drag and drop of files from the system (demo in Widgets->Drag and Drop)
• Add font loading from the system or from a file
• Automatically save and restore context size, position and dock state
• Clear pressed keyboard keys when losing focus
• Demo: add a docking example in Configuration->Configuration
• Don't include software mouse cursors in the font texture
• Don't show data following '##' in the context window title
• Enable window and table settings persistence
• Ensure contexts are created with a size of at least 10x10
• Examples: wait until the next defer cycle before creating the context
• InputText: Don't corrupt text using Unicode planes 1-16 (codepoints beyond 0xffff)
• Keep ListClipper objects alive for more than one frame (as long as they're used)
• macOS: detect focus …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.4

- API/reaper_imgui.ext
• Create a dedicated platform window for each ImGui virtual window
• Demo: move docking example to 'Window options'
• Fix removing focus using SetWindowFocusEx
• macOS: count vertical coordinates from the top of the primary monitor
• Switch to Dear ImGui v1.83's 'docking' branch
• Re-implement docking into REAPER using ImGui's docking branch's beta API
• Update the Lua, EEL2, Python and C++ examples
• Windows: detect HiDPI scaling changes when docked in REAPER (Per-Monitor v2 mode)
• Windows: fix positioning of the system's Input Method Editor (IME) on HiDPI monitors
API changes:
• Add Col_DockingPreview, Col_DockingEmptyBg
• Add ConfigFlags_DockingEnable, WindowFlags_NoDocking
• Add IsWindowDocked, GetWindowDockID, SetNextWindowDockID
• Add SetWindow* functions without a window name …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.5beta

- API/reaper_imgui.ext
• Demo: improve ImGui docker handling in the docking example
• Docking: don't recreate the platform window when switching active ImGui window in the same dock
• Docking: keep docker open if there are other windows sharing it when undocking a window by dragging
• Documentation: mark p_* arguments as both read and write [p=2459747]
• Documentation: use Consolas font to improve readability on Windows
• Font: enable loading color data from fonts
• Font: Report font loading errors in the first function call of the frame
• macOS: give focus to the platform window under mouse on right/middle click [p=2460594]
• Save settings of active contexts when unloading the extension [p=2461792]
API changes:
• Remove WindowFlags_NoBringToFrontOnFocus (no-op since v0.5) [p=2462354]
> Release ReaImGui: ReaScript binding for Dear ImGui v0.5.3

- API/reaper_imgui.ext
• Docking: wait until after the left mouse button is released before closing the REAPER docker
• Documentation: fix parsing of links at the very end of the help text
• Python binding: Fix a syntax error in imgui_python.py [#4]
• Windows: fix a possible crash during (un)docking of a window
API changes:
• Add ShowAboutWindow
> Release ReaImGui: ReaScript binding for Dear ImGui v0.5.4

- API/reaper_imgui.ext
• Demo: disable docking combo box when docking is unavailable
• macOS: fix topmost state being reset when REAPER regains focus
• Update Dear ImGui to v1.84.1 (release notes at https://github.com/ocornut/imgui/releases/tag/v1.84)
API changes:
• Add BeginDisabled/EndDisabled and StyleVar_DisabledAlpha
• Add DetachFont
• Add TableColumnFlags_Disabled and TableColumnFlags_NoHeaderLabel
• Add WindowFlags_TopMost [p=2468716][p=2471188][p=2476740]
• Remove ColorEditFlags__OptionsDefault
> Release ReaImGui: ReaScript binding for Dear ImGui v0.5.5

- API/reaper_imgui.ext
• Demo: rename the 'Top most' checkbox to 'Always on top'
• Documentation: add ImGui_Font* to the list of ValidatePtr's supported types
• Documentation: fix the main content area not filling the browser window's full width
• Documentation: revert marking p_open arguments as non-optional
• Windows: disable topmost when the REAPER app is inactive
• Windows: fix topmost being reset when REAPER is unminimized [p=2476936]
API changes:
• Add the text filter API [p=2476922]
> Release ReaImGui: ReaScript binding for Dear ImGui v0.5.6

- API/reaper_imgui.ext
• Font: downgrade FreeType to 2.10.4 as workaround for a crash in 2.11.0 on Windows [p=2486019][p=2486079]
• Linux: fix window visibility when dragging them over REAPER's main window [p=2486034]
> Release ReaImGui: ReaScript binding for Dear ImGui v0.5.8

- API/ak5k_ReaBlink.ext
Puppet mode related performance tweaks.
ReaBlink Monitor script file now has commented out placeholder line for enabling Master mode.
> Release ReaBlink: Ableton Link REAPER plug-in extension v0.4.4

- API/reaper_imgui.ext
• Docker: fix no rendering on macOS if opened within the first 3 frames of the context
• Docker: obey WindowFlags_NoFocusOnAppearing if set on any hosted windows
• Fix the main viewport having a zero position and size [p=2498028]
• Fix WindowFlags_NoFocusOnAppearing not having an effect within the first 3 frames
• Update to Dear ImGui v1.85
API changes:
• Add DockHierarchy and NoPopupHierarchy in both FocusedFlags and HoveredFlags
• Add ShowStackToolWindow (also Demo->Tools->Stack Tool)
• Remove GetWindowContentRegionWidth
> Release ReaImGui: ReaScript binding for Dear ImGui v0.5.9

- API/reaper_imgui.ext
• Update to Dear ImGui v1.86 <https://github.com/ocornut/imgui/releases/tag/v1.86>
API changes:
• Add GetMouseClickedCount
• Add ListClipper_ForceDisplayRangeByIndices
> Release ReaImGui: ReaScript binding for Dear ImGui v0.5.10

- API/reaper_imgui.ext
• Add support for mouse buttons 4 and 5 (3 and 4 in the API)
• Distinguish between Left/Right modifier keys and Enter/KeypadEnter keys
• Fix a crash when failing to initialize the OpenGL renderer for docked windows
• Migrate mouse and keyboard input to v1.87's new event-based API
• Reduce the minimum required version of OpenGL to 3.1
• Suspend keyboard and mouse input when the defer timer is blocked (eg. modal dialog)
• Update to Dear ImGui v1.87 (https://github.com/ocornut/imgui/releases/tag/v1.87)
• Linux: connect Dear ImGui's clipboard to the system clipboard
• Linux: fix crashes when recovering from OpenGL initialization errors
• Linux: fix inverted NWSE/NESW cursors
• Linux: implement IME and proper Unicode character input support
• Linux: workaround black/flashing windows when …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.6.0

- API/reaper_imgui.ext
• Export main demo functions to scripts including the demo file
• Fix broken anti-aliasing after attaching a font
• Fix the first frame of every window being rendered blank
• Linux: fix crash when quitting REAPER while docked ReaImGui windows are open
• Linux: repair file drag and drop
• Windows: prevent incorrect focus when closing windows out of order
> Release ReaImGui: ReaScript binding for Dear ImGui v0.6.1

- API/reaper_imgui.ext
• Fix a crash when destroying list clippers while a different context is active
• Fix empty points array crashing DrawList_Add{Polyline,ConvexPolyFilled}
• Linux: restore broken key up/down events when an IME is active
• macOS: allow OpenGL software renderering for wider compatibility
• macOS: fix keyboard input when holding down a mouse button and the "Allow keyboard commands when mouse-editing" setting is disabled [p=2552296]
• Windows: receive Alt key events when "Prevent ALT key from focusing main menu" is enabled
API changes:
• DrawList_PathArcTo: fix incorrect default value for 'num_segments' when omitted
• Revert "Fix DrawList_AddTextEx not using the default bitmap font when font == nil" from v0.6
> Release ReaImGui: ReaScript binding for Dear ImGui v0.6.2

- API/reaper_imgui.ext
• Add backward-compatibility script imgui.lua
• Fix broken mouse inputs after destroying a window while a mouse button is down
• Implement window transparency (requires REAPER v6.55+ on Linux)
• Increase maximum object allocation limit to 1000
• Linux: harden v0.6's improved mouse and keyboard input (now requires REAPER v6.57+)
• Optimize object pointer validation (about 2x faster)
• Patch dear imgui to enable background alpha and corner rounding for top-level windows
• Update dear imgui to v1.88 <https://github.com/ocornut/imgui/releases/tag/v1.88>
API changes:
• Add ColorConvert{Double4ToU32,U32ToDouble4}
• Add DebugTextEncoding
• Add GetWindowViewport
• Add HoveredFlags_NoNavOverride
• Add ShowDebugLogWindow
• Combo and ListBox: use null bytes for delimiting items as in vanilla dear …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.7

- API/reaper_imgui.ext
• Add a translation layer for running gfx scripts on ReaImGui (gfx2imgui.lua)
• Enable SetNextWindowBgAlpha for all windows
• Fix corrupted font texture in contexts having windows using different DPI scaling
• Fix potential crash on exit in REAPER < 6.67 due to plugin registration keys being invalidated [reapack#56]
• macOS: fix pressed keyboard keys getting stuck when opening modal dialogs
• macOS: fix rescaling when moving windows to a monitor using a different DPI setting
• macOS: fix windows not moving above the menu bar on macOS 12 [p=2579183]
• macOS: gain keyboard focus when switching from another docker tab
API changes:
• Add the DrawListSplitter API
> Release ReaImGui: ReaScript binding for Dear ImGui v0.7.1

- FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext
Apple ARM64 related memory bug fix, maybe other systems too.
Dropped highly experimental and optional PDC mode check feature for now.
> Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.3.2

- API/reaper_imgui.ext
• Fix window under the window under mouse getting hovered for 1 frame on mouse release
• macOS: fix crash when the context is destroyed while a window is docked
• macOS: fix framebuffer size not updating when switching from another docker tab
• macOS: fix noninitial windows not gaining focus on open
API changes:
• Add GetWindowDpiScale
gfx2imgui:
• Add GFX2IMGUI_NO_BLIT_PREMULTIPLY option [p=2609372]
• Fix nearest font selection when sizes smaller than requested are loaded [p=2609372]
• Keep alive fonts while they're actively being drawn from a blitted buffer [p=2609372]
• Warn when subtituting font for the default one
> Release ReaImGui: ReaScript binding for Dear ImGui v0.7.2

- API/reaper_imgui.ext
• Add a user settings page in Preferences > Plug-ins > ReaImGui:
- Option to disable restoration of saved settings ("safe mode")
- Option to select which graphics renderer to use
• Display indirect errors in a custom, more user-friendly dialog
• Implement bitmap image loading (PNG and JPEG from a file or memory) and image sets (per-DPI variants)
• macOS: add a Metal renderer (new default, requires El Capitan or newer)
• Share GPU textures with all windows in the same context (except on Linux due to a GDK 3 limitation)
• Update dear imgui to v1.89.1 <https://github.com/ocornut/imgui/releases/tag/v1.89> and <https://github.com/ocornut/imgui/releases/tag/v1.89.1>
• Windows: add a Direct3D 10 renderer (new default)
• Windows: disable minimizing and use the tool window style when decorations …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.8

- API/reaper_imgui.ext
• imgui.lua: add shims for dear imgui 1.89's obsoleted window boundary extension via SetCursorPos/SetCursorScreenPos
• macOS: fix the Metal renderer crashing (observed on macOS 12 ARM)
> Release ReaImGui: ReaScript binding for Dear ImGui v0.8.1

- API/reaper_imgui.ext
• Add actions to toggle boolean settings
• Adjust the top docker's hit box for the tabbar, transport and toolbar above
• Fix a crash when undocking by dragging the top-left corner triangle
• Reduce memory usage when docking is enabled
• Update dear imgui to v1.89.2 <https://github.com/ocornut/imgui/releases/tag/v1.89.2>
imgui.lua:
• Extend 0.8 shims for window boundary extension to cover End{Popup,Table,Tooltip}
• Fix 0.7 shim of CaptureKeyboardFromApp [p=2633349]
• Fix 0.8 shims eating the return values of TableNext{Column,Row} and TableSetColumnIndex [p=2632656]
• Fix 0.8 shims making EndGroup move the cursor to the wrong Y position [p=2632446]
API changes:
• Remove IsWindowCollapsed (broken since v0.5)
> Release ReaImGui: ReaScript binding for Dear ImGui v0.8.3

- API/reaper_imgui.ext
• Fill the HWND text of docked windows with the tab name [p=2649553]
• Fix "Too many vertices in ImDrawList" assertion when adding many draw calls during the first 2 frames of a context
• Fix a crash when opening a window more than 1 minute after the last one in the same context [p=2639537]
• Fix two cases of stuck mouse buttons and keyboard keys after closing windows
• Ignore warnings when loading PNG images
• Lua demo: replace `r.ImGui_` prefix with `ImGui.`
• macOS: fix a crash when destroying a window immediately after receiving focus
• macOS: fix stuck buttons and keys after a native menu is opened
• macOS: update window position when resizing via native decorations
• Re-raise the minimum OpenGL version to 3.2
• Update dear imgui to v1.89.3 …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.8.4

- FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext
REAPER v6.72 or later required.
Disables PDC for monitored signalchain to achieve lower latencies or to allow more processing while monitoring.
"P_PDCLIMIT" can be set as floating point number, e.g. "0.5" to set target latency of 0.5 times current buffer/block size.
> Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.4.0

- API/reaper_imgui.ext
• Add a new API for running EEL programs
• Collect all errors in a single report window
• Disable ConfigVar_InputTrickleEventQueue by default
• Fix duplicate error reports when failing to end a frame
• Remove global object count limit (limit context attachments instead)
• Update to dear imgui v1.89.4 <https://github.com/ocornut/imgui/releases/tag/v1.89.4>
• macOS: fix stuck keys when undocking while a key is down
• macOS: follow the "Control+left-click emulates right-click" setting [t=277197]
• Windows: fix a regression in the OpenGL renderer causing crashes [p=2656531]
Documentation:
• Add a table of contents of the entire category tree
• Insert links for references with trailing wildcards (eg. StyleVar_*)
gfx2imgui:
• Add REAPER v6.75's gfx.getchar second return value
• Implement …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.8.5

- API/reaper_imgui.ext
• Add a button to restore default settings in the preferences page
• Don't give focus to the first setting when opening the preferences page [t=277729]
• Enable docking by default (ConfigFlags_DockingEnable) and expose a user setting
• Fix 1-frame flicker after uploading a new texture
• Fix a use-after-free when calling an EEL function after an assertion failure
• Fix crashes when removing/uploading textures every frame [p=2663379]
• Fix name conflict between the ImGui_Image type and function in the C++ header
• Revert "disable ConfigVar_InputTrickleEventQueue by default" [p=2664743]
• Update to dear imgui v1.89.5 <https://github.com/ocornut/imgui/releases/tag/v1.89.5>
API changes:
• Move the C++ API functions to a ImGui namespace
> Release ReaImGui: ReaScript binding for Dear ImGui v0.8.6

- API/reaper_imgui.ext
• macOS: restore accidentally disabled clipboard I/O
> Release ReaImGui: ReaScript binding for Dear ImGui v0.8.6.1

- FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext
Requires REAPER 6.79.
Prefixes bypassed FX names with `llm: `. This allows ReaLlm to keep track of duplicates.
> Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.5.0

- API/ak5k_ReaBlink.ext
Update to Ableton Link 3.0.6
Transport stopping related crash fix in Puppet mode
> Release ReaBlink: Ableton Link REAPER plug-in extension v0.4.5

- API/ak5k_ReaBlink.ext
Restored release build compatibility with older Windows versions.
> Release ReaBlink: Ableton Link REAPER plug-in extension v0.4.6

- API/reaper_imgui.ext
• Fix a crash when windows are closed out of ownership order while a mouse button is down
• macOS: fix the x86_64 version not containing FreeType2 since 0.8.7 [p=2694907]
> Release ReaImGui: ReaScript binding for Dear ImGui v0.8.7.2

- API/reaper_imgui.ext
• Report stored size when opening a docked window [p=2700189]
• macOS and Windows: fix a memory leak and potential crash when the renderer fails to initialize
• macOS: fix a crash when pressing mouse buttons higher than 5
• macOS: fix a memory leak and a potential crash in the Metal renderer when images are incorrectly re-created every frame while a window is occluded [p=2698614]
• macOS: fix mouse events not reaching REAPER after opening a native menu while a mouse button is down then pressing another button
• macOS: release mouse capture on window focus changes [p=2695756]
• macOS: send a single right-click event when handling the "Control+left-click emulates right-click" setting
> Release ReaImGui: ReaScript binding for Dear ImGui v0.8.7.3

- API/reaper_imgui.ext
• Fix a crash when undocking via the context menu since 0.8.7.3
> Release ReaImGui: ReaScript binding for Dear ImGui v0.8.7.4

- API/reaper_imgui.ext
• Fix compatibility of file drag and drop with dear imgui v1.89.4
• Focus new docked windows when they are the only tab in the docker [p=2724239]
• Windows: fix detection of the "multimonitor aware" HiDPI mode on Windows 8.1 [p=2724812]
• Windows: fix windows not staying in place after moving under certain monitor scales [p=2724640]
gfx2imgui:
• Fix replacing images after (re)initializing gfx
• Harden gradrect to gracefully handle bogus Infinity/NaN delta arguments
> Release ReaImGui: ReaScript binding for Dear ImGui v0.8.7.5

- Control Surfaces/ak5k_ReaSolotus REAPER Solo bus extension.ext
Mix and Solo busses no longer reset their positions between sessions.
> Release ReaSolotus: REAPER Solo bus extension v0.1.7

- API/ak5k_ReaBlink.ext
Near-complete rewrite of Master/Puppet engine
New quantized launch method
Thread-safe; no conflicts with other extensions
Now works also in tandem with external MIDI sync
Updated ReaBlink Monitor
WASAPI audio might be usable in exclusive mode
Smoother sync correction
Some new API functions
> Release ReaBlink: Ableton Link REAPER plug-in extension v0.5.0

- API/ak5k_ReaBlink.ext
removed SetMakeReaperGoBrrr
replaced with custom timer
> Release ReaBlink: Ableton Link REAPER plug-in extension v0.5.1

- API/ak5k_ReaBlink.ext
Local Ableton Link session is now created/joined only after first call to Blink_SetEnabled(). E.g when starting ReaBlink_Monitor.lua script.
> Release ReaBlink: Ableton Link REAPER plug-in extension v0.5.2

- API/reaper_imgui.ext
• Fix a brief display of uninitialized pixels when opening docked windows
• Fix a crash when REAPER quits while a frame is still open
• Fix TableGetColumnSortSpecs accepting invalid negative indices
• Handle font size truncation when computing rendering scale
• macOS: fix fallback for missing font families in recent OS versions
• macOS: fix window position desync when changing monitor resolution in recent OS versions [p=2732554]
• Linux: fix windows not staying in place under certain monitor scales [#13]
• Linux: repair HiDPI scaling (regression from v0.8) [p=2752987]
> Release ReaImGui: ReaScript binding for Dear ImGui v0.8.7.6

- API/ak5k_ReaBlink.ext
Improved compatibility with older REAPER versions
> Release ReaBlink: Ableton Link REAPER plug-in extension v0.5.3

- API/ak5k_ReaBlink.ext
fix dummy pre-roll regions clean-up
> Release ReaBlink: Ableton Link REAPER plug-in extension v0.5.4

- API/reaper_imgui.ext
• Add an action to open the HTML documentation
• Add a setting to disable hardware acceleration (Direct3D on Windows and OpenGL on macOS only) [p=2763726]
• Add saving and restoring UI state in REAPER screensets
• Document the minimum compatible version of each API function
• Fix list clippers not always using the specified context
• Fix v0.8.7's incorrect shim of ListClipper_ForceDisplayRangeByIndices
• Implement error detection in the OpenGL renderer
• Improve accuracy when scaling up fonts for HiDPI
• Limit image width/height to 8192 pixels
• Reduce the maximum count of per-context attachments to 1024
• Report an error when using an EEL callback function outside of a callback
• Support toggling WindowFlags_NoInputs after window creation
• Throw an error when resources are wastefully …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.9

- API/reaper_imgui.ext
• Fix 0.9 not switching the active font texture to the current DPI in dockers
• Fix 0.9 shims letting through unknown virtual key codes and asserting
• macOS: fix incorrect clipping in the Metal renderer if the clip rect's origin is smaller than the window's position
• Windows: repair drag-docking over floating dockers
> Release ReaImGui: ReaScript binding for Dear ImGui v0.9.0.2

- API/reaper_imgui.ext
• Add a LuaCATS definition file for IDE language servers (in the Releases page on GitHub)
• Clarify error messages occurring during font loading are font-related [p=2776476]
• Differentiate between integer/number in the documented Lua signatures
• Document CollapsingHeader's and Selectable's p_* parameters as optional
• Fix assertion failure when setting an empty drag/drop payload
• Fix incorrect values of ModFlags_{Alt,Shift,Super} in 0.8 shims
• Prevent stuck keys when keyboard capture is released from an action's global shortcut key [p=2765259]
• Remove ReaImGui_Hello World.eel from the ReaPack package
• Update to dear imgui v1.90.6 <https://github.com/ocornut/imgui/releases/tag/v1.90.6>
C++ bindings:
• Annotate Begin* and Create* functions as [[nodiscard]]
• Fix all pointer parameters …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.9.1

- API/reaper_imgui.ext
• Add experimental Zig bindings
• Fix the 0.7 shim of CaptureKeyboardFromApp [p=2790175]
• Fix the Viewport API not starting a frame [p=2783450]
• Update to dear imgui 1.90.9
API changes:
• Add ChildFlags_NavFlattened
• Add Col_Tab{SelectedOverline,DimmedSelectedOverline} and TabBarFlags_DrawSelectedOverline
• Add ConfigFlags_NoKeyboard
• Add CreateImageFromLICE (support bitmaps created using JS_LICE_CreateBitmap only)
• Add InputTextFlags_{Display,Parse}EmptyRefVal
• Add optional 'flags' parameter to CreateImageFromMem
• Add Shortcut, SetNextItemShortcut and InputFlags_*.
• Add SliderFlags_WrapAround
• Add TableGetHoveredColumn
• Rename Col_TabActive to _TabSelected, _TabUnfocused to _TabDimmed and TabUnfocusedActive to _TabDimmedSelected
• Rename DragDropFlags_SourceAutoExpirePayload to …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.9.2

- Control Surfaces/ak5k_ReaSolotus REAPER Solo bus extension.ext
New separate action called "ReaSolotus Init" to initialized project. Projects will have to be manually initialized. Displays error message, if ReaSolotus is enabled, but project is not initialized.
> Release ReaSolotus: REAPER Solo bus extension v0.2.0

- API/reaper_imgui.ext
• Fix sub-30ms fast double-clicks landing on the window under [p=2795708]
• Repair the LuaCATS definition file
• macOS: fix compatibility with macOS 15 "Sequoia" [p=2809649]
• macOS: fix a crash when a texture is is bigger than Metal limits
• macOS: fix restoration of Ctrl when regaining focus and right-click emulation is enabled
• macOS: fix stuck right-click emulation when unfocusing while Ctrl is down
• macOS: forward mousewheel events when WindowFlags_NoInputs is set [p=2799779]
API changes:
• Add CreateFontFromMem
> Release ReaImGui: ReaScript binding for Dear ImGui v0.9.3

- API/reaper_imgui.ext
• Fix a crash when saving screensets after more than one context shared an ID
• Select better font fallbacks in the HTML documentation
• Linux: fix a crash when opening a window on the same frame images got garbage-collected
> Release ReaImGui: ReaScript binding for Dear ImGui v0.9.3.2

- FX/ak5k_ReaLlm REAPER Low latency monitoring plug-in extension.ext
Tracks with names including 'Llm' are treated as monitored inputs.
Added Windows ARM build
> Release ReaLlm: REAPER Low latency monitoring plug-in extension v0.7.0

- API/reaper_imgui.ext
• Accurately detect when script execution is suspended (REAPER v7.28+ only)
• Fix default flags in Demo > Widgets > Text Input > Multi-line
• Fix empty lines in imgui_defs.lua due to empty section help text
• Fix gaining logical focus when the OS window gets it from a window outside the context
• Fix omitting ColorPick4's ref_col parameter
• Fix splash screen detection being off by one frame
• Limit user window sizes to 8192px per axis to avoid crashes
• macOS: report hit-testing transparency to SWELL's WindowFromPoint
• Windows: fix Alt key input while holding down a mouse button when "Allow keyboard commands when mouse-editing" is disabled
gfx2imgui:
• Accept passing a nil and other non-string names to gfx.init
• Fix gfx.getchar returning a nil second value when closing
• Fix unattached …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.9.3.3

- API/reaper_imgui.ext
• Automatically fallback to another system font when encountering missing glyphs
• Decouple line height from the font size (compute value from the font)
• Display the current window name in asynchronous error reports
• Enable keyboard navigation by default and add user settings
• Improve accuracy of anti-aliasing on HiDPI monitors
• Increase EEL user string length limit from 16384 to 65536 (same as REAPER)
• Lift requirement to Attach fonts before use & before a frame starts
• Lift U+0020 to U+00FF restriction of usable glyphs from fonts [#5]
• Make the font size be the em square's height for consistency between fonts
• Reduce the default vertical frame padding to 2px
• Report clean error messages without assertion decorations when possible
• Silence unnecessary secondary assertion …
> Release ReaImGui: ReaScript binding for Dear ImGui v0.10

- API/reaper_imgui.ext
• macOS: fix font selection when a system font file contains mixed widths variations or family names
• Windows: repair IME character input [p=2883427]
> Release ReaImGui: ReaScript binding for Dear ImGui v0.10.0.1

- Extensions/reaper-oss_SWS.ext
Actions:
• Fix a crash in "SWS: Reset item rate, preserving length, clear 'preserve pitch'" when a selected item contains an empty take (issue 1939)
Cycle actions:
• Add support for REAPER v7.40's new Crossfade Editor section
Hit detection:
• Fix Y offset in hit detection of envelope points and segments [#954]
• Implement hit detection of envelope points within automation items [#922]
List view: (issue 1947)
• Fix incorrect width when enabling columns and more than one is hidden
• Fix position of inserted columns ignoring preceding hidden ones
• Preserve custom order when adding or removing columns
Notes:
• Clear cached previous text when closing the window [#1942]
MIDI Editor:
• Repair regression caused by the MIDI Editor HiDPI fix on Windows and macOS [p=2858128]
> Release SWS/S&M extension v2.14.0.5-beta

- Extensions/reaper-oss_SWS.ext
• Disable "SWS: Redo/Undo zoom" actions by default to remove unnecessary CPU overhead
• Fix excessive CPU usage when many hidden tracks have visual spacers [p=2883811]
> Release SWS/S&M extension v2.14.0.6

- API/reaper_imgui.ext
• Update modifiers on window focus instead of only on mouse down
• Linux: fix creation of textures pending an update on new windows [p=2884972]
• Linux: remove focus when none of the hidden windows are active
• macOS: fix selection of the default font face within files containing variations on macOS 11 & 12 [p=2887560]
• Windows: ignore system fonts using the Microsoft Symbol encoding [p=2884504]
> Release ReaImGui: ReaScript binding for Dear ImGui v0.10.0.2

- Extensions/reaper-oss_SWS.ext
Hit detection:
- Repair hit detection of envelope segment in non-first tracks [p=2889179]
- Update automation item point hit testing to support REAPER v7.46 API fixes [p=2888669]
Notes:
- Fix empty notes when re-opening the window after closing it using an action [#1965]
> Release SWS/S&M extension v2.14.0.7
